// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The severity of the event described in a log entry, expressed as one of the
/// standard severity levels listed below.  For your reference, the levels are
/// assigned the listed numeric values. The effect of using numeric values other
/// than those listed is undefined.
///
/// You can filter for log entries by severity.  For example, the following
/// filter expression will match log entries with severities `INFO`, `NOTICE`,
/// and `WARNING`:
///
///     severity > DEBUG AND severity <= WARNING
///
/// If you are writing log entries, you should map other severity encodings to
/// one of these standard levels. For example, you might map all of Java's FINE,
/// FINER, and FINEST levels to `LogSeverity.DEBUG`. You can preserve the
/// original severity level in the log entry payload if you wish.
public enum LogSeverity: Codable, Equatable, Sendable {
  /// (0) The log entry has no assigned severity level.
  case `default`
  /// (100) Debug or trace information.
  case debug
  /// (200) Routine information, such as ongoing status or performance.
  case info
  /// (300) Normal but significant events, such as start up, shut down, or
  /// a configuration change.
  case notice
  /// (400) Warning events might cause problems.
  case warning
  /// (500) Error events are likely to cause problems.
  case error
  /// (600) Critical events cause more severe problems or outages.
  case critical
  /// (700) A person must take an action immediately.
  case alert
  /// (800) One or more systems are unusable.
  case emergency
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .`default`
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .`default`: return 0
    case .debug: return 100
    case .info: return 200
    case .notice: return 300
    case .warning: return 400
    case .error: return 500
    case .critical: return 600
    case .alert: return 700
    case .emergency: return 800
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .`default`: return "DEFAULT"
    case .debug: return "DEBUG"
    case .info: return "INFO"
    case .notice: return "NOTICE"
    case .warning: return "WARNING"
    case .error: return "ERROR"
    case .critical: return "CRITICAL"
    case .alert: return "ALERT"
    case .emergency: return "EMERGENCY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LogSeverity/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DEFAULT": self = .`default`
    case "DEBUG": self = .debug
    case "INFO": self = .info
    case "NOTICE": self = .notice
    case "WARNING": self = .warning
    case "ERROR": self = .error
    case "CRITICAL": self = .critical
    case "ALERT": self = .alert
    case "EMERGENCY": self = .emergency
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LogSeverity/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .`default`
    case 100: self = .debug
    case 200: self = .info
    case 300: self = .notice
    case 400: self = .warning
    case 500: self = .error
    case 600: self = .critical
    case 700: self = .alert
    case 800: self = .emergency
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .`default`: return try container.encode(0)
    case .debug: return try container.encode(100)
    case .info: return try container.encode(200)
    case .notice: return try container.encode(300)
    case .warning: return try container.encode(400)
    case .error: return try container.encode(500)
    case .critical: return try container.encode(600)
    case .alert: return try container.encode(700)
    case .emergency: return try container.encode(800)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
